import '../data/models/recipe_model.dart';

final List<Recipe> recipes = [
Recipe(
title: 'Chicken Parmesan',
imageUrl: 'https://example.com/chicken-parmesan.jpg',
ingredients: [
'4 boneless, skinless chicken breasts',
'1 cup breadcrumbs',
'1/2 cup grated Parmesan cheese',
'1 tsp garlic powder',
'1/2 tsp salt',
'1/4 tsp black pepper',
'1 egg, beaten',
'2 cups marinara sauce',
'1 cup shredded mozzarella cheese',
],
steps: [
'Preheat oven to 375°F.',
'In a shallow dish, combine breadcrumbs, Parmesan cheese, garlic powder, salt, and black pepper.',
'Dip chicken breasts in beaten egg, then coat in breadcrumb mixture.',
'Place chicken breasts in a greased baking dish.',
'Bake for 25 minutes, then top each chicken breast with marinara sauce and mozzarella cheese.',
'Bake for an additional 10 minutes, or until cheese is melted and bubbly.',
'Serve hot and enjoy!',
],
calories: 450,
duration: 45,
),
Recipe(
title: 'Spaghetti Carbonara',
imageUrl: 'https://example.com/spaghetti-carbonara.jpg',
ingredients: [
'1 lb spaghetti',
'4 oz pancetta, diced',
'4 cloves garlic, minced',
'4 large eggs',
'1 cup grated Parmesan cheese',
'1/4 cup chopped fresh parsley',
'Salt and pepper, to taste',
],
steps: [
'Cook spaghetti according to package directions. Drain and reserve 1 cup of pasta water.',
'In a large skillet, cook pancetta over medium heat until crispy. Add garlic and cook for an additional 1-2 minutes.',
'In a small bowl, whisk together eggs, Parmesan cheese, parsley, salt, and pepper.',
'Add cooked spaghetti to the skillet with the pancetta and garlic. Remove from heat and quickly toss with the egg mixture. Add reserved pasta water as needed to create a creamy sauce.',
'Serve hot and enjoy!',
],
calories: 560,
duration: 30,
),
Recipe(
title: 'Spaghetti with Meatballs',
imageUrl: 'https://example.com/spaghetti-meatballs.jpg',
ingredients: [
'1 pound spaghetti',
'1 pound ground beef',
'1/2 cup breadcrumbs',
'1/2 cup grated Parmesan cheese',
'1/4 cup chopped fresh parsley',
'1 egg, beaten',
'1 tsp garlic powder',
'1/2 tsp salt',
'1/4 tsp black pepper',
'4 cups marinara sauce',
],
steps: [
'Cook spaghetti according to package instructions.',
'In a large bowl, combine ground beef, breadcrumbs, Parmesan cheese, parsley, egg, garlic powder, salt, and black pepper.',
'Form meat mixture into 1-inch balls.',
'In a large skillet, cook meatballs over medium heat until browned on all sides.',
'Add marinara sauce to skillet and simmer for 10-15 minutes.',
'Serve meatballs and sauce over spaghetti and enjoy!',
],
calories: 550,
duration: 50,
),
  Recipe(
  title: 'Classic Lasagna',
  imageUrl: 'https://example.com/lasagna.jpg',
  ingredients: [
    '1 pound ground beef',
    '1 pound Italian sausage',
    '1/2 cup chopped onion',
    '3 cloves garlic, minced',
    '2 cans tomato sauce',
    '2 cans diced tomatoes',
    '2 tsp dried basil',
    '1 tsp fennel seeds',
    '1 tsp salt',
    '1/4 tsp black pepper',
    '12 lasagna noodles',
    '16 oz ricotta cheese',
    '2 cups shredded mozzarella cheese',
    '1/4 cup grated Parmesan cheese',
  ],
  steps: [
    'Preheat oven to 375°F.',
    'In a large skillet, cook ground beef, Italian sausage, onion, and garlic over medium heat until browned.',
    'Stir in tomato sauce, diced tomatoes, basil, fennel seeds, salt, and black pepper. Simmer for 10-15 minutes.',
    'Cook lasagna noodles according to package instructions.',
    'In a separate bowl, combine ricotta cheese and 1 cup of mozzarella cheese.',
    'Spread 1 cup of meat sauce in the bottom of a 9x13 inch baking dish.',
    'Layer 4 lasagna noodles on top of sauce, followed by 1/3 of the ricotta cheese mixture, and 1 cup of meat sauce.',
    'Repeat layers of noodles, ricotta cheese mixture, and meat sauce twice more.',
    'Top with remaining 1 cup of mozzarella cheese and grated Parmesan cheese.',
    'Bake for 25-30 minutes, or until cheese is melted and bubbly.',
    'Let lasagna cool for a few minutes before slicing and serving.',
  ],
  calories: 700,
  duration: 75,
),
];